CREATE wawdrugs.MEDICINE
(
  ID INTEGER NOT NULL,
  NAME VARCHAR (100) NOT NULL,
  PRICE VARCHAR (20) NOT NULL,
  GROUP VARCHAR (20) NOT NULL,
  PRIMARY KEY (ID)
);

GRANT ALL ON TABLE wawdrugs.MEDICINE TO postgres;

ALTER TABLE wawdrugs.MEDICINE TO postgres;